### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by dvstudio** [thetylerwolf/sketchfindatagen#2]
Apologies if  I'm doing something wrong... 

I'm selecting a shape, then plug'ins>generate Chart... and.. nothing...

using Sketch 3.2.2 on OSX 10.10

Seems to have loaded correctly.. wondering if I missed something. Anyone else?

Thanks in advance.

--Dave

**Comment by thetylerwolf** [comment]
Does a prompt come up when you select "generate chart"?

**Comment by dvstudio** [comment]
Oh hey.. thanks for checking in…

I’m not getting any of the prompts as you laid out in the instrux.

Weird …

**Comment by thetylerwolf** [comment]
Very unusual. I have two idea.
1. When was the last time you closed and re-opened Sketch? That's resolved issues for me in the past
2. If you can send me an error log, that would be a huge help to resolve the problem. Can you follow this to capture the error log?
http://www.bohemiancoding.com/sketch/support/developer/01-introduction/03.html

**Comment by dvstudio** [comment]
Wow... I totally missed your last message... Just tried it again...

Here's the log:

3/31/15 11:17:17.021 AM Sketch[4737]: Couldn't #import script './functions/inputs.js'
3/31/15 11:17:17.022 AM Sketch[4737]: Couldn't #import script './globals/chartTypes.js'
3/31/15 11:17:17.393 AM Generate Chart (Sketch Plugin)[4737]: ReferenceError: Can't find variable: askForInput.
Plugin “Generate Chart”, line 7.
» input = askForInput('Generate how many [points,series]?'); «
3/31/15 11:17:17.394 AM Sketch[4737]: Exception: {
    column = 20;
    line = 7;
    sourceURL = "/Users/druehontz/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Generate Chart.sketchplugin";
}

Hope this helps!

**Comment by thetylerwolf** [comment]
That is very helpful. It looks like you grabbed the "Generate Chart.sketchplugin" file and put it in your plugins folder. The plugin has a few core dependencies between both the generate table and generate chart functionalities (files in the "functions" and "globals" folders), so you need the whole project folder in your Plugins folder for it to work.

If you want to reduce the number of files you take, I can point out which ones you don't need.

**Comment by dvstudio** [comment]
Awesome!  All good!

Thanks man!!!
