### ISSUE TITLE
Include screenshots

### ISSUE THREAD

**Issue by phoenixbox** [thetylerwolf/sketchfindatagen#3]
Hey there,

it would be great to have screenshots to show a mockup with the data. The link below is how to do it.

[Include screenshots in github](http://stackoverflow.com/questions/10189356/how-to-add-screenshot-to-readmes-in-github-repository)

TLDR: Create a `screenshots` branch off of master, then commit the screenshots to it and reference them with relative paths from the `README.md` in master

**Comment by thetylerwolf** [comment]
Hey, I didn't see this till now. I'll try to get something together in the next few days.

**Comment by thetylerwolf** [comment]
Thanks for the tip. Just added a nice screenshot
